[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "malleon"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mitmproxy>=10",
]

[tool.setuptools.packages.find]
include = ["malleon*"]

[project.scripts]
malleon = "malleon.cli:main"
